FROM python:3.11-slim
# Install curl (and clean apt cache)
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*
    
RUN pip install pandas jinja2 requests SPARQLWrapper
WORKDIR templates/testing
EXPOSE 7001
CMD ["bash"]
